class Pandemic {
    constructor(A, B, C, DAYS_OF_SICKNESS, PERCENTEAGE_BECOMING_CARRIER, PERCENTAGE_BECOMING_IMMUNE, DAYS_IMMUNE_PASS, PERCENTAGE_INFECTION, DAYS_INCUBATION) {
        this.A = A;
        this.B = B;
        this.C = C;
        this.DAYS_OF_SICKNESS = DAYS_OF_SICKNESS;
        this.DAYS_INCUBATION = DAYS_INCUBATION;
        this.PERCENTAGE_INFECTION = PERCENTAGE_INFECTION;
        this.PERCENTEAGE_BECOMING_CARRIER = PERCENTEAGE_BECOMING_CARRIER;
        this.PERCENTAGE_BECOMING_IMMUNE = PERCENTAGE_BECOMING_IMMUNE;
        this.DAYS_IMMUNE_PASS = DAYS_IMMUNE_PASS;        
    }
}