class Society{
    constructor(V_MAX, MAX_FORCE, PERCENTAGE_QUARANTINED, HYGIENE, POPULATION, PERCENTAGE_INITIAL_SICKNESS, SIGHT, SEPERATION, COHESION, ALIGNMENT, OPENING, PERIMETER) {
        this.V_MAX= V_MAX;
        this.MAX_FORCE= MAX_FORCE;
        this.PERCENTAGE_QUARANTINED= PERCENTAGE_QUARANTINED;
        this.HYGIENE= HYGIENE;
        this.POPULATION= POPULATION;
        this.PERCENTAGE_INITIAL_SICKNESS= PERCENTAGE_INITIAL_SICKNESS;
        this.SIGHT= SIGHT;
        this.SEPERATION= SEPERATION;
        this.COHESION= COHESION;
        this.ALIGNMENT= ALIGNMENT;
        this.OPENING= OPENING;
        this.PERIMETER= PERIMETER;
    }
}