class Pandemic {
    constructor(DEATH_PERCENTAGE, DAYS_OF_SICKNESS, PERCENTEAGE_BECOMING_CARRIER, PERCENTAGE_BECOMING_IMMUNE, DAYS_IMMUNE_PASS) {
        this.DEATH_PERCENTAGE = DEATH_PERCENTAGE;
        this.DAYS_OF_SICKNESS = DAYS_OF_SICKNESS;
        this.PERCENTEAGE_BECOMING_CARRIER = PERCENTEAGE_BECOMING_CARRIER;
        this.PERCENTAGE_BECOMING_IMMUNE = PERCENTAGE_BECOMING_IMMUNE;
        this.DAYS_IMMUNE_PASS = DAYS_IMMUNE_PASS;        
    }
}